
'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Data.EntityClient
Imports System.ComponentModel
Imports System.Xml.Serialization
Imports System.Runtime.Serialization

<Assembly: EdmSchemaAttribute("e1ac460d-a27d-4a91-b6ed-1e87202b7a40")>
#Region "EDM Relationship Metadata"
<Assembly: EdmRelationshipAttribute("DataCarModel", "FK_StudentsCars", "Students", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(Student), "Cars", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(Car), True)>

#End Region

#Region "Contexts"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
Public Partial Class DataCarEntities
    Inherits ObjectContext

    #Region "Constructors"

    ''' <summary>
    ''' Initializes a new DataCarEntities object using the connection string found in the 'DataCarEntities' section of the application configuration file.
    ''' </summary>
    Public Sub New()
        MyBase.New("name=DataCarEntities", "DataCarEntities")
    MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new DataCarEntities object.
    ''' </summary>
    Public Sub New(ByVal connectionString As String)
        MyBase.New(connectionString, "DataCarEntities")
    MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new DataCarEntities object.
    ''' </summary>
    Public Sub New(ByVal connection As EntityConnection)
        MyBase.New(connection, "DataCarEntities")
    MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    #End Region

    #Region "Partial Methods"

    Partial Private Sub OnContextCreated()
    End Sub

    #End Region

    #Region "ObjectSet Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property Cars() As ObjectSet(Of Car)
        Get
            If (_Cars Is Nothing) Then
                _Cars = MyBase.CreateObjectSet(Of Car)("Cars")
            End If
            Return _Cars
        End Get
    End Property

    Private _Cars As ObjectSet(Of Car)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property Students() As ObjectSet(Of Student)
        Get
            If (_Students Is Nothing) Then
                _Students = MyBase.CreateObjectSet(Of Student)("Students")
            End If
            Return _Students
        End Get
    End Property

    Private _Students As ObjectSet(Of Student)

    #End Region
    #Region "AddTo Methods"

    ''' <summary>
    ''' Deprecated Method for adding a new object to the Cars EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToCars(ByVal car As Car)
        MyBase.AddObject("Cars", car)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the Students EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToStudents(ByVal student As Student)
        MyBase.AddObject("Students", student)
    End Sub

    #End Region
End Class

#End Region
#Region "Entities"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="DataCarModel", Name:="Car")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
<KnownTypeAttribute(GetType(Cars_TimeCars))>
Public Partial Class Car
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new Car object.
    ''' </summary>
    ''' <param name="id">Initial value of the Id property.</param>
    ''' <param name="brand">Initial value of the Brand property.</param>
    ''' <param name="model">Initial value of the Model property.</param>
    ''' <param name="tagId">Initial value of the TagId property.</param>
    ''' <param name="picture">Initial value of the Picture property.</param>
    ''' <param name="student_Id">Initial value of the Student_Id property.</param>
    Public Shared Function CreateCar(id As Global.System.String, brand As Global.System.String, model As Global.System.String, tagId As Global.System.String, picture As Global.System.String, student_Id As Global.System.String) As Car
        Dim car as Car = New Car
        car.Id = id
        car.Brand = brand
        car.Model = model
        car.TagId = tagId
        car.Picture = picture
        car.Student_Id = student_Id
        Return car
    End Function

    #End Region
    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Id() As Global.System.String
        Get
            Return _Id
        End Get
        Set
            If (_Id <> Value) Then
                OnIdChanging(value)
                ReportPropertyChanging("Id")
                _Id = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("Id")
                OnIdChanged()
            End If
        End Set
    End Property

    Private _Id As Global.System.String
    Private Partial Sub OnIdChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnIdChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Brand() As Global.System.String
        Get
            Return _Brand
        End Get
        Set
            OnBrandChanging(value)
            ReportPropertyChanging("Brand")
            _Brand = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("Brand")
            OnBrandChanged()
        End Set
    End Property

    Private _Brand As Global.System.String
    Private Partial Sub OnBrandChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnBrandChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Model() As Global.System.String
        Get
            Return _Model
        End Get
        Set
            OnModelChanging(value)
            ReportPropertyChanging("Model")
            _Model = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("Model")
            OnModelChanged()
        End Set
    End Property

    Private _Model As Global.System.String
    Private Partial Sub OnModelChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnModelChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property TagId() As Global.System.String
        Get
            Return _TagId
        End Get
        Set
            OnTagIdChanging(value)
            ReportPropertyChanging("TagId")
            _TagId = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("TagId")
            OnTagIdChanged()
        End Set
    End Property

    Private _TagId As Global.System.String
    Private Partial Sub OnTagIdChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnTagIdChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Picture() As Global.System.String
        Get
            Return _Picture
        End Get
        Set
            OnPictureChanging(value)
            ReportPropertyChanging("Picture")
            _Picture = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("Picture")
            OnPictureChanged()
        End Set
    End Property

    Private _Picture As Global.System.String
    Private Partial Sub OnPictureChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnPictureChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Student_Id() As Global.System.String
        Get
            Return _Student_Id
        End Get
        Set
            OnStudent_IdChanging(value)
            ReportPropertyChanging("Student_Id")
            _Student_Id = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("Student_Id")
            OnStudent_IdChanged()
        End Set
    End Property

    Private _Student_Id As Global.System.String
    Private Partial Sub OnStudent_IdChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnStudent_IdChanged()
    End Sub

    #End Region
    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("DataCarModel", "FK_StudentsCars", "Students")>
    Public Property Student() As Student
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Student)("DataCarModel.FK_StudentsCars", "Students").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Student)("DataCarModel.FK_StudentsCars", "Students").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property StudentReference() As EntityReference(Of Student)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Student)("DataCarModel.FK_StudentsCars", "Students")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Student)("DataCarModel.FK_StudentsCars", "Students", value)
            End If
        End Set
    End Property

    #End Region
End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="DataCarModel", Name:="Cars_TimeCars")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Cars_TimeCars
    Inherits Car
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new Cars_TimeCars object.
    ''' </summary>
    ''' <param name="id">Initial value of the Id property.</param>
    ''' <param name="brand">Initial value of the Brand property.</param>
    ''' <param name="model">Initial value of the Model property.</param>
    ''' <param name="tagId">Initial value of the TagId property.</param>
    ''' <param name="picture">Initial value of the Picture property.</param>
    ''' <param name="student_Id">Initial value of the Student_Id property.</param>
    ''' <param name="dateTime">Initial value of the DateTime property.</param>
    Public Shared Function CreateCars_TimeCars(id As Global.System.String, brand As Global.System.String, model As Global.System.String, tagId As Global.System.String, picture As Global.System.String, student_Id As Global.System.String, dateTime As Global.System.DateTime) As Cars_TimeCars
        Dim cars_TimeCars as Cars_TimeCars = New Cars_TimeCars
        cars_TimeCars.Id = id
        cars_TimeCars.Brand = brand
        cars_TimeCars.Model = model
        cars_TimeCars.TagId = tagId
        cars_TimeCars.Picture = picture
        cars_TimeCars.Student_Id = student_Id
        cars_TimeCars.DateTime = dateTime
        Return cars_TimeCars
    End Function

    #End Region
    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property DateTime() As Global.System.DateTime
        Get
            Return _DateTime
        End Get
        Set
            OnDateTimeChanging(value)
            ReportPropertyChanging("DateTime")
            _DateTime = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("DateTime")
            OnDateTimeChanged()
        End Set
    End Property

    Private _DateTime As Global.System.DateTime
    Private Partial Sub OnDateTimeChanging(value As Global.System.DateTime)
    End Sub

    Private Partial Sub OnDateTimeChanged()
    End Sub

    #End Region
End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="DataCarModel", Name:="Student")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Student
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new Student object.
    ''' </summary>
    ''' <param name="id">Initial value of the Id property.</param>
    ''' <param name="firstName">Initial value of the FirstName property.</param>
    ''' <param name="lastName">Initial value of the LastName property.</param>
    ''' <param name="dome">Initial value of the Dome property.</param>
    ''' <param name="studyField">Initial value of the StudyField property.</param>
    ''' <param name="phone">Initial value of the Phone property.</param>
    Public Shared Function CreateStudent(id As Global.System.String, firstName As Global.System.String, lastName As Global.System.String, dome As Global.System.String, studyField As Global.System.String, phone As Global.System.String) As Student
        Dim student as Student = New Student
        student.Id = id
        student.FirstName = firstName
        student.LastName = lastName
        student.Dome = dome
        student.StudyField = studyField
        student.Phone = phone
        Return student
    End Function

    #End Region
    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Id() As Global.System.String
        Get
            Return _Id
        End Get
        Set
            If (_Id <> Value) Then
                OnIdChanging(value)
                ReportPropertyChanging("Id")
                _Id = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("Id")
                OnIdChanged()
            End If
        End Set
    End Property

    Private _Id As Global.System.String
    Private Partial Sub OnIdChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnIdChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property FirstName() As Global.System.String
        Get
            Return _FirstName
        End Get
        Set
            OnFirstNameChanging(value)
            ReportPropertyChanging("FirstName")
            _FirstName = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("FirstName")
            OnFirstNameChanged()
        End Set
    End Property

    Private _FirstName As Global.System.String
    Private Partial Sub OnFirstNameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnFirstNameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property LastName() As Global.System.String
        Get
            Return _LastName
        End Get
        Set
            OnLastNameChanging(value)
            ReportPropertyChanging("LastName")
            _LastName = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("LastName")
            OnLastNameChanged()
        End Set
    End Property

    Private _LastName As Global.System.String
    Private Partial Sub OnLastNameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnLastNameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Dome() As Global.System.String
        Get
            Return _Dome
        End Get
        Set
            OnDomeChanging(value)
            ReportPropertyChanging("Dome")
            _Dome = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("Dome")
            OnDomeChanged()
        End Set
    End Property

    Private _Dome As Global.System.String
    Private Partial Sub OnDomeChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnDomeChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property StudyField() As Global.System.String
        Get
            Return _StudyField
        End Get
        Set
            OnStudyFieldChanging(value)
            ReportPropertyChanging("StudyField")
            _StudyField = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("StudyField")
            OnStudyFieldChanged()
        End Set
    End Property

    Private _StudyField As Global.System.String
    Private Partial Sub OnStudyFieldChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnStudyFieldChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Phone() As Global.System.String
        Get
            Return _Phone
        End Get
        Set
            OnPhoneChanging(value)
            ReportPropertyChanging("Phone")
            _Phone = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("Phone")
            OnPhoneChanged()
        End Set
    End Property

    Private _Phone As Global.System.String
    Private Partial Sub OnPhoneChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnPhoneChanged()
    End Sub

    #End Region
    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("DataCarModel", "FK_StudentsCars", "Cars")>
     Public Property Cars() As EntityCollection(Of Car)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Car)("DataCarModel.FK_StudentsCars", "Cars")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Car)("DataCarModel.FK_StudentsCars", "Cars", value)
            End If
        End Set
    End Property

    #End Region
End Class

#End Region

