
'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Data.EntityClient
Imports System.ComponentModel
Imports System.Xml.Serialization
Imports System.Runtime.Serialization

<Assembly: EdmSchemaAttribute("fd3cfbe4-d0e7-4846-b86a-fcd4f9202c8c")>
#Region "EDM Relationship Metadata"
<Assembly: EdmRelationshipAttribute("DataCarModel", "StudentsCars", "Students", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(Students), "Cars", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(Cars))>

#End Region

#Region "Contexts"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
Public Partial Class DataCarModelContainer
    Inherits ObjectContext

    #Region "Constructors"

    ''' <summary>
    ''' Initializes a new DataCarModelContainer object using the connection string found in the 'DataCarModelContainer' section of the application configuration file.
    ''' </summary>
    Public Sub New()
        MyBase.New("name=DataCarModelContainer", "DataCarModelContainer")
    MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new DataCarModelContainer object.
    ''' </summary>
    Public Sub New(ByVal connectionString As String)
        MyBase.New(connectionString, "DataCarModelContainer")
    MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new DataCarModelContainer object.
    ''' </summary>
    Public Sub New(ByVal connection As EntityConnection)
        MyBase.New(connection, "DataCarModelContainer")
    MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    #End Region

    #Region "Partial Methods"

    Partial Private Sub OnContextCreated()
    End Sub

    #End Region

    #Region "ObjectSet Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property Students() As ObjectSet(Of Students)
        Get
            If (_Students Is Nothing) Then
                _Students = MyBase.CreateObjectSet(Of Students)("Students")
            End If
            Return _Students
        End Get
    End Property

    Private _Students As ObjectSet(Of Students)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property Cars() As ObjectSet(Of Cars)
        Get
            If (_Cars Is Nothing) Then
                _Cars = MyBase.CreateObjectSet(Of Cars)("Cars")
            End If
            Return _Cars
        End Get
    End Property

    Private _Cars As ObjectSet(Of Cars)

    #End Region
    #Region "AddTo Methods"

    ''' <summary>
    ''' Deprecated Method for adding a new object to the Students EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToStudents(ByVal students As Students)
        MyBase.AddObject("Students", students)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the Cars EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToCars(ByVal cars As Cars)
        MyBase.AddObject("Cars", cars)
    End Sub

    #End Region
End Class

#End Region
#Region "Entities"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="DataCarModel", Name:="Cars")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
<KnownTypeAttribute(GetType(TimeCars))>
Public Partial Class Cars
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new Cars object.
    ''' </summary>
    ''' <param name="id">Initial value of the Id property.</param>
    ''' <param name="brand">Initial value of the Brand property.</param>
    ''' <param name="model">Initial value of the Model property.</param>
    ''' <param name="tagId">Initial value of the TagId property.</param>
    ''' <param name="picture">Initial value of the Picture property.</param>
    Public Shared Function CreateCars(id As Global.System.String, brand As Global.System.String, model As Global.System.String, tagId As Global.System.String, picture As Global.System.String) As Cars
        Dim cars as Cars = New Cars
        cars.Id = id
        cars.Brand = brand
        cars.Model = model
        cars.TagId = tagId
        cars.Picture = picture
        Return cars
    End Function

    #End Region
    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Id() As Global.System.String
        Get
            Return _Id
        End Get
        Set
            If (_Id <> Value) Then
                OnIdChanging(value)
                ReportPropertyChanging("Id")
                _Id = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("Id")
                OnIdChanged()
            End If
        End Set
    End Property

    Private _Id As Global.System.String
    Private Partial Sub OnIdChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnIdChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Brand() As Global.System.String
        Get
            Return _Brand
        End Get
        Set
            OnBrandChanging(value)
            ReportPropertyChanging("Brand")
            _Brand = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("Brand")
            OnBrandChanged()
        End Set
    End Property

    Private _Brand As Global.System.String
    Private Partial Sub OnBrandChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnBrandChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Model() As Global.System.String
        Get
            Return _Model
        End Get
        Set
            OnModelChanging(value)
            ReportPropertyChanging("Model")
            _Model = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("Model")
            OnModelChanged()
        End Set
    End Property

    Private _Model As Global.System.String
    Private Partial Sub OnModelChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnModelChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property TagId() As Global.System.String
        Get
            Return _TagId
        End Get
        Set
            OnTagIdChanging(value)
            ReportPropertyChanging("TagId")
            _TagId = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("TagId")
            OnTagIdChanged()
        End Set
    End Property

    Private _TagId As Global.System.String
    Private Partial Sub OnTagIdChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnTagIdChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Picture() As Global.System.String
        Get
            Return _Picture
        End Get
        Set
            OnPictureChanging(value)
            ReportPropertyChanging("Picture")
            _Picture = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("Picture")
            OnPictureChanged()
        End Set
    End Property

    Private _Picture As Global.System.String
    Private Partial Sub OnPictureChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnPictureChanged()
    End Sub

    #End Region
    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("DataCarModel", "StudentsCars", "Students")>
    Public Property Student() As Students
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Students)("DataCarModel.StudentsCars", "Students").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Students)("DataCarModel.StudentsCars", "Students").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property StudentReference() As EntityReference(Of Students)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Students)("DataCarModel.StudentsCars", "Students")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Students)("DataCarModel.StudentsCars", "Students", value)
            End If
        End Set
    End Property

    #End Region
End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="DataCarModel", Name:="Students")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Students
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new Students object.
    ''' </summary>
    ''' <param name="id">Initial value of the Id property.</param>
    ''' <param name="firstName">Initial value of the FirstName property.</param>
    ''' <param name="lastName">Initial value of the LastName property.</param>
    ''' <param name="dome">Initial value of the Dome property.</param>
    ''' <param name="studyField">Initial value of the StudyField property.</param>
    ''' <param name="phone">Initial value of the Phone property.</param>
    Public Shared Function CreateStudents(id As Global.System.String, firstName As Global.System.String, lastName As Global.System.String, dome As Global.System.String, studyField As Global.System.String, phone As Global.System.String) As Students
        Dim students as Students = New Students
        students.Id = id
        students.FirstName = firstName
        students.LastName = lastName
        students.Dome = dome
        students.StudyField = studyField
        students.Phone = phone
        Return students
    End Function

    #End Region
    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Id() As Global.System.String
        Get
            Return _Id
        End Get
        Set
            If (_Id <> Value) Then
                OnIdChanging(value)
                ReportPropertyChanging("Id")
                _Id = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("Id")
                OnIdChanged()
            End If
        End Set
    End Property

    Private _Id As Global.System.String
    Private Partial Sub OnIdChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnIdChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property FirstName() As Global.System.String
        Get
            Return _FirstName
        End Get
        Set
            OnFirstNameChanging(value)
            ReportPropertyChanging("FirstName")
            _FirstName = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("FirstName")
            OnFirstNameChanged()
        End Set
    End Property

    Private _FirstName As Global.System.String
    Private Partial Sub OnFirstNameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnFirstNameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property LastName() As Global.System.String
        Get
            Return _LastName
        End Get
        Set
            OnLastNameChanging(value)
            ReportPropertyChanging("LastName")
            _LastName = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("LastName")
            OnLastNameChanged()
        End Set
    End Property

    Private _LastName As Global.System.String
    Private Partial Sub OnLastNameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnLastNameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Dome() As Global.System.String
        Get
            Return _Dome
        End Get
        Set
            OnDomeChanging(value)
            ReportPropertyChanging("Dome")
            _Dome = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("Dome")
            OnDomeChanged()
        End Set
    End Property

    Private _Dome As Global.System.String
    Private Partial Sub OnDomeChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnDomeChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property StudyField() As Global.System.String
        Get
            Return _StudyField
        End Get
        Set
            OnStudyFieldChanging(value)
            ReportPropertyChanging("StudyField")
            _StudyField = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("StudyField")
            OnStudyFieldChanged()
        End Set
    End Property

    Private _StudyField As Global.System.String
    Private Partial Sub OnStudyFieldChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnStudyFieldChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Phone() As Global.System.String
        Get
            Return _Phone
        End Get
        Set
            OnPhoneChanging(value)
            ReportPropertyChanging("Phone")
            _Phone = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("Phone")
            OnPhoneChanged()
        End Set
    End Property

    Private _Phone As Global.System.String
    Private Partial Sub OnPhoneChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnPhoneChanged()
    End Sub

    #End Region
    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("DataCarModel", "StudentsCars", "Cars")>
     Public Property Cars() As EntityCollection(Of Cars)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Cars)("DataCarModel.StudentsCars", "Cars")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Cars)("DataCarModel.StudentsCars", "Cars", value)
            End If
        End Set
    End Property

    #End Region
End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="DataCarModel", Name:="TimeCars")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class TimeCars
    Inherits Cars
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new TimeCars object.
    ''' </summary>
    ''' <param name="id">Initial value of the Id property.</param>
    ''' <param name="brand">Initial value of the Brand property.</param>
    ''' <param name="model">Initial value of the Model property.</param>
    ''' <param name="tagId">Initial value of the TagId property.</param>
    ''' <param name="picture">Initial value of the Picture property.</param>
    ''' <param name="dateTime">Initial value of the DateTime property.</param>
    Public Shared Function CreateTimeCars(id As Global.System.String, brand As Global.System.String, model As Global.System.String, tagId As Global.System.String, picture As Global.System.String, dateTime As Global.System.DateTime) As TimeCars
        Dim timeCars as TimeCars = New TimeCars
        timeCars.Id = id
        timeCars.Brand = brand
        timeCars.Model = model
        timeCars.TagId = tagId
        timeCars.Picture = picture
        timeCars.DateTime = dateTime
        Return timeCars
    End Function

    #End Region
    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property DateTime() As Global.System.DateTime
        Get
            Return _DateTime
        End Get
        Set
            OnDateTimeChanging(value)
            ReportPropertyChanging("DateTime")
            _DateTime = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("DateTime")
            OnDateTimeChanged()
        End Set
    End Property

    Private _DateTime As Global.System.DateTime
    Private Partial Sub OnDateTimeChanging(value As Global.System.DateTime)
    End Sub

    Private Partial Sub OnDateTimeChanged()
    End Sub

    #End Region
End Class

#End Region

